train_data: ../data/dataset/train.tsv
dev_data: ../data/dataset/val.tsv


model:
  encoder:
    embedding_dim: 100
    hidden_size: 100
    input_dropout: 0.3

  decoder:
    embedding_dim: 100
    hidden_size: 200
    input_dropout: 0.3

trainer:
  batch_size: 4
  random_seed: 42

train:
  n_epochs: 50
  teacher_forcing_ratio: 0.2

